let thirdPoint = document.querySelectorAll('.menu-item')[1];
let secondPoint = document.querySelectorAll('.menu-item')[2];
let fifthPoint = document.createElement('li');
fifthPoint.classList.add('menu-item');
fifthPoint.textContent = 'Пятый пункт';
document.querySelector('.menu').insertBefore(secondPoint, thirdPoint);
document.querySelector('.menu').appendChild(fifthPoint);
document.body.style.background = 'url(../img/apple_true.jpg) center no-repeat';
let title = document.querySelector('.title');
let adv = document.querySelector('.adv');
document.querySelectorAll('.column')[1].replaceChild(title, adv);
let answer = prompt('Как вы относитесть к технике apple?');
document.querySelector('.prompt').textContent = answer;
title.textContent = 'Мы продаем только подлинную технику Apple';